/** Deliberate alpha public surface. Storage, events and provisional runtime stay internal. */
export { defineApplication, validateApplication } from './application/index.ts';
export type { ApplicationDefinition } from './application/index.ts';
export type { RunProfile, RunRecord, ResolvedInput } from './session/index.ts';
export type { TaskRecord } from './task/index.ts';
export type { ArtifactRecord, ArtifactRef, ArtifactContract, ArtifactRequirement, ArtifactConsumptionRecord, PayloadRef } from './artifact/index.ts';
export type { PluginDescriptor } from './plugin/index.ts';
export type { JsonValue } from './json.ts';
export type { ActorRef, RuntimeRef } from './actor/index.ts';
export { connectLoom, createRequest, describeEntry, discoverEntries } from './agent.ts';
export type { AgentConnectionOptions, AgentHostBinding, DiscoveryFilter } from './agent.ts';
export type { AgentRequest, EntryContract, EntryPresentation, DataSchema } from './invocation.ts';
export type { AgentReceipt, ParticipantSummary } from './agent-receipt.ts';
export type { TaskInspection, TaskSnapshot } from './inspection.ts';
export { createTask } from './task-service.ts';
export type { HostTaskStore, SessionHost, SessionPlan, NativeSessionHandle } from './host.ts';
export { ContainerFailure } from './failure/index.ts';
export type { FailureCode, FailureRecord } from './failure/index.ts';
export { registerSafeDiagnostics } from './failure/diagnostic.ts';
export type { SafeDiagnostic } from './failure/diagnostic.ts';
